### ISSUE TITLE
QTQuick Controls not being loaded

### ISSUE THREAD

**Issue by Jayy-Dev** [nicefaa6waa/genshin-sddm-theme#20]
Installed the theme but ran into issues when testing it.

SDDM test shows this:
--
sddm-greeter --test-mode --theme /usr/share/sddm/themes/genshin-sddm-theme
High-DPI autoscaling Enabled
Reading from "/usr/local/share/xsessions/bspwm.desktop"
Reading from "/usr/share/xsessions/bspwm.desktop"
Loading theme configuration from "/usr/share/sddm/themes/genshin-sddm-theme/theme.conf"
Socket error:  "QLocalSocket::connectToServer: Invalid name"
Loading file:///usr/share/sddm/themes/genshin-sddm-theme/Main.qml...
file:///usr/share/sddm/themes/genshin-sddm-theme/Main.qml:5:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered 
     import QtQuick.Controls 2.12 
     ^
file:///usr/share/sddm/themes/genshin-sddm-theme/Main.qml:5:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered 
     import QtQuick.Controls 2.12 
     ^
Fallback to embedded theme
file:///usr/lib/qt/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/theme/Main.qml:41:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Adding view for "eDP-1" QRect(0,0 1920x1080)

**Comment by nicefaa6waa** [comment]
Hi.It seems like a bug related to Qt 5.15.2.I found a forum page where it was mentioned but it was never fixed until Qt6.Try installing and adding Qt6 flag as i mentioned in Readme file or if you did remove it from config file.Keep me updated i will try to fix this issue

**Comment by nicefaa6waa** [comment]
Also try reinstalling the dependancies or try another sddm theme to see if they are working or not.

**Comment by Jayy-Dev** [comment]
Installed `qt5-quickcontrols2` which made the theme works. But issues like video not displaying and doors slow are my current issues.


https://github.com/nicefaa6waa/genshin-sddm-theme/assets/105900291/1f3c149a-3ee7-4f41-99c8-7beddfd17680

**Comment by nicefaa6waa** [comment]
Hm it is actually not the slow door issue i mentioned before.In slow door issue they usually just started really late but in your case it only loads first and the last frame.It may be an issue related to bad qt plugins.Try reinstalling **qt5-multimedia**.Also i saw you are using same username with your password.I don't know your credentials but your username and password should be same with your linux user.If it is different just change it in /components/credentials.txt.If you are stuck on log in screen when starting just read the wiki of this repository.There aren't any issues related to video files in error log.The errors are usually about layout issues which will be fixed later but have nothing to do with your problem.Update your package database and run pacman -Qs for me
`
sudo pacman -Syu
pacman -Qs gst-libav phonon-qt5-gstreamer gst-plugins-good qt5-quickcontrols qt5-graphicaleffects qt5-multimedia qt6-base
`
also please show me your /etc/sddm.conf file

**Comment by Jayy-Dev** [comment]
The video is just showing the 
```
sddm-greeter --test-mode --theme /usr/share/sddm/themes/genshin-sddm-theme
``` 
so I can test themes without actually logging out my session.

/etc/sddm.conf:

```
[Autologin]
# Whether sddm should automatically log back into sessions when they exit
Relogin=false

# Name of session file for autologin session (if empty try last logged in)
Session=

# Username for autologin session
User=


[General]
# Which display server should be used.
# Valid values are: x11, x11-user, wayland. Wayland support is experimental
DisplayServer=x11

# Comma-separated list of environment variables to be set
GreeterEnvironment=

# Halt command
HaltCommand=/usr/bin/systemctl poweroff

# Input method module
InputMethod=

# Comma-separated list of Linux namespaces for user session to enter
Namespaces=

# Initial NumLock state. Can be on, off or none.
# If property is set to none, numlock won't be changed
# NOTE: Currently ignored if autologin is enabled.
Numlock=none

# Reboot command
RebootCommand=/usr/bin/systemctl reboot


[Theme]
# Current theme name
Current=genshin-sddm-theme

# Cursor size used in the greeter
CursorSize=

# Cursor theme used in the greeter
CursorTheme=

# Number of users to use as threshold
# above which avatars are disabled
# unless explicitly enabled with EnableAvatars
DisableAvatarsThreshold=7

# Enable display of custom user avatars
EnableAvatars=true

# Global directory for user avatars
# The files should be named <username>.face.icon
FacesDir=/usr/share/sddm/faces

# Font used in the greeter
Font=

# Theme directory path
ThemeDir=/usr/share/sddm/themes


[Users]
# Default $PATH for logged in users
DefaultPath=/usr/local/bin:/usr/bin:/bin

# Comma-separated list of shells.
# Users with these shells as their default won't be listed
HideShells=

# Comma-separated list of users that should not be listed
HideUsers=

# Maximum user id for displayed users
MaximumUid=60513

# Minimum user id for displayed users
MinimumUid=1000

# Remember the session of the last successfully logged in user
RememberLastSession=true

# Remember the last successfully logged in user
RememberLastUser=true

# When logging in as the same user twice, restore the original session, rather than create a new one
ReuseSession=true


[Wayland]
# Path of the Wayland compositor to execute when starting the greeter
CompositorCommand=weston --shell=fullscreen-shell.so

# Enable Qt's automatic high-DPI scaling
EnableHiDPI=true

# Path to a script to execute when starting the desktop session
SessionCommand=/usr/share/sddm/scripts/wayland-session

# Comma-separated list of directories containing available Wayland sessions
SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions

# Path to the user session log file
SessionLogFile=.local/share/sddm/wayland-session.log


[X11]
# Path to a script to execute when starting the display server
DisplayCommand=/usr/share/sddm/scripts/Xsetup

# Path to a script to execute when stopping the display server
DisplayStopCommand=/usr/share/sddm/scripts/Xstop

# Enable Qt's automatic high-DPI scaling
EnableHiDPI=true

# Arguments passed to the X server invocation
ServerArguments=-nolisten tcp

# Path to X server binary
ServerPath=/usr/bin/X

# Path to a script to execute when starting the desktop session
SessionCommand=/usr/share/sddm/scripts/Xsession

# Comma-separated list of directories containing available X sessions
SessionDir=/usr/local/share/xsessions,/usr/share/xsessions

# Path to the user session log file
SessionLogFile=.local/share/sddm/xorg-session.log

# Path to Xephyr binary
XephyrPath=/usr/bin/Xephyr

MinimumQtVersion=6.2.0
```

**Comment by nicefaa6waa** [comment]
Try removing `MinimumQtVersion-6.2.0` then reinstall gst libav.Also before reinstalling gst add line `Environment=QT_QUICK_BACKEND=software` under `[X11] as 
```
[X11]
# Path to a script to execute when starting the display server
DisplayCommand=/usr/share/sddm/scripts/Xsetup
Environment=QT_QUICK_BACKEND=software

Rest ofthe code....
```
If adding software environment variable fixes video playback issue then just reinstall gst and its packages as i mentioned in the previous comment.

**Comment by nicefaa6waa** [comment]
If qt-multimedia was installed incorrectly or was missing dependancies it should give error when importing it.So i think your issue is higly likely related to your video backend.Change your config files as i recommended and keep me updated.I will try to fix your issue as soon as possible.

**Comment by Jayy-Dev** [comment]
Reinstalled all of the dependencies and added the software environment variable, but still the same as in the video.

**Comment by nicefaa6waa** [comment]
Can you try to install another sddm theme that uses video backgrounds.Try [this](https://github.com/3ximus/aerial-sddm-theme) for example.

**Comment by Jayy-Dev** [comment]
A bit laggy but it works

https://github.com/nicefaa6waa/genshin-sddm-theme/assets/105900291/75321cbf-7114-4560-b0c8-f404fa6a7aba

**Comment by nicefaa6waa** [comment]
Hm the lag makes it almost identical to mine.I think it is somehow related to your video player backend settings.You are either using a build of Qt that doesn't have hardware acceleration enabled, or your system doesn't have the proper hardware for Qt to accelerate decoding and playback.Remove Environment=QT_QUICK_BACKEND=software.Try changing QtMultimedia 5.13 to QtMultimedia 5.7 in Main.qml.My videos are h265 NVenc so it may be a little bit hard for gstreamer to run this codec.I honestly can't tell you how to fix it.Never experienced this issue in my test setups but still i will try to find a way and update you.Meanwhile let me know if you can find a way to fix it.

**Comment by Jayy-Dev** [comment]
My system seems to be using QSV h264 for encoding and decoding, maybe the problem is for decoding?

**Comment by nicefaa6waa** [comment]
It may be.Can you replace a random h264 video  with background video to see if it's working.I don't think it will tho since aerial themes videos were h264 i guess.

**Comment by Jayy-Dev** [comment]
so I was testing the videos but it doesn't work except for the doors
![Screenshot_2024-01-28_13-36-57](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/105900291/16118f6d-2db9-4e62-8868-9a0100d0ce32)

**Comment by nicefaa6waa** [comment]
Oh so it was codecs.You can just change h265 to webm using ffmpeg but i don't think it will work since door videos are still laggy.Check how you can fixt this codec issue

**Comment by nicefaa6waa** [comment]
Closing this issue since there are no comments,If you have more questions just create a new issue
