### ISSUE TITLE
Cannot clone

### ISSUE THREAD

**Issue by zhum** [nicefaa6waa/genshin-sddm-theme#22]
```
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                  
error: failed to fetch some objects from 'https://github.com/nicefaa6waa/genshin-sddm-theme.git/info/lfs'
```

**Comment by nicefaa6waa** [comment]
oh my bad.I will replace lfs with megadl in the next update including script and some layout foxes too.I will upload it in like 20 hours.Until then you can just git clone instead of git lfs clone and download videos from drive link in manual installation.Sorry for the inconvenience.

**Comment by nicefaa6waa** [comment]
Replaced git lfs with megatools.So just use normal git clone now.Fixed with the latest update
