### ISSUE TITLE
May I request support for redhat based OS (fedora)?

### ISSUE THREAD

**Issue by Misaka-0x447f** [nicefaa6waa/genshin-sddm-theme#24]
Really nice SDDM Theme but can't figure out what deps I need to install

**Comment by nicefaa6waa** [comment]
Hi. You might have tried using manual installation and finding the dependencies yourself, but from what I understand, you encountered difficulties. My apologies for this oversight. I realized I added auto-installation support for Kubuntu but not for Fedora, which is indeed more widely known and used. I will rectify this by adding Fedora to the auto-installation process within the next day or two. You won't need to install the dependencies manually before running the auto-installation; it will prompt you for your OS and install all the necessary packages automatically. Have a good day, and thank you for your help in improving this theme!

**Comment by nicefaa6waa** [comment]
Also, instead of waiting until then, you can use this command:
```
sudo dnf install gstreamer1.0-libav gstreamer1-plugins-base gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-gtk gstreamer1-plugins-ugly qt5-qtquickcontrols qt5-qtgraphicaleffects qt5-qtmultimedia qt6-qtbase megatools
```

If it didn't work try this
```
sudo dnf install gstreamer1-libav qml-module-qtquick-controls2 qml-module-qtgraphicaleffects qt5-qtmultimedia6-plugins qt6-base ffmpeg megatools
```

   Please keep in mind that Fedora does not have a qt5-default package like Debian/Ubuntu or Arch, as it handles Qt versions differently. Please keep me updated if anything goes wrong. The Fedora installation process is more complicated, so I may have to install Fedora on one of my workspaces to fix compatibility issues. Thank you for your patience.

**Comment by nicefaa6waa** [comment]
Okay so for Fedora you can use 
```
sudo dnf install gstreamer1-plugins-base gstreamer1-plugins-good gstreamer1-plugins-bad-free gstreamer1-plugins-bad-free-gtk qt5-qtquickcontrols qt5-quickcontrols2 qt5-qtgraphicaleffects qt5-qtmultimedia qt5-qtmultimedia-5.15.12.-1.fc39 qt6-qtbase megatools
```
Tested it on my Fedora 39 system and it worked.If you are using a different Fedora version keep in mind that it requires minimum Fedora 38 and up to Fedora 41.Just replace qt-multimedia version with the stable version for your Fedora.
you can chek all supported versions [here](https://src.fedoraproject.org/rpms/qt5-qtmultimedia)

About the installation script Fedora support will be added soon.Have a great day reopen this issue if you have any other questions or you still need help!

**Comment by nicefaa6waa** [comment]
Also while you can use these libraries to install the theme i highly recommend to wait for auto installation since downloading videos disabling virtual keyboard and stuff is a little bit hard.Manual installation is not easy but it is your choice to do whatever you want
