### ISSUE TITLE
Question: Is there any other way (other than using Virtual Private Network to access Mega) to upload and download these videos?

### ISSUE THREAD

**Issue by CryoMarshal** [nicefaa6waa/genshin-sddm-theme#30]
Seems like the country I'm living right now **doesn't** allow me to access some of the foreign websites, including Mega. Which stopped me from downloading these video files and return to these errors.
![Screenshot_20240519_110552](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/63281870/df1acfea-e6f5-4df1-8842-32faafeb43a3)

OS Run-time: Ubuntu 24.04 in KDE Session(I installed KDE Plasma Environment by myself which works alongside with GNOME)

**Comment by nicefaa6waa** [comment]
First of all, I apologize for the delayed reply; I didn't have access to my PC for the past two days. Secondly, I really love your Furina profile picture! <3

Regarding your issue, I have included Google Drive links in the Manual Installation Instructions where you can download the videos manually. If Google Drive is also inaccessible in your country, please let me know of any file hosting websites that you can use, and I will upload the videos there for you.

Have a great day! <3

**Comment by CryoMarshal** [comment]
However, if possible, I can use iCloud instead.

**Comment by nicefaa6waa** [comment]
Thanks i will upload to icloud and share the link with you asap

**Comment by nicefaa6waa** [comment]
For some reason iCloud didn't work.You can try this tho
https://www.filemail.com/d/qlsaebxpvsmhcuo
Let me know if it works <3

**Comment by CryoMarshal** [comment]
OK, That works, although it is quite slow downloading, but I can wait.

**Comment by nicefaa6waa** [comment]
Thanks for your patience.If you have any more issues or questions please re-open this issue.Thank you again for using genshin sdmm theme
