### ISSUE TITLE
Question about an error i am getting.

### ISSUE THREAD

**Issue by RoxBlox3** [nicefaa6waa/genshin-sddm-theme#37]
Hello,
I wanted to try out this theme. But when i do the installation steps and select it as the login theme. I get the base login screen and an error that says:
The current theme cannot be loaded due to the errors below, please select another theme

file:///usr/share/sddm/themes/genshin-sddm-theme/Main.qml:5:1module "QtQuick.Controls" version 2.12 is not installed

I don't know if it's an error on my side.
I'm on Garuda linux KDE lite which is an arch based distro.

**Comment by RoxBlox3** [comment]
And just now i saw your closed issue about it sorry. The command fixed it thanks.

**Comment by RoxBlox3** [comment]
Had to reinstall the plugin with sudo pacman -S qt5-quickcontrols2 --overwrite '*'

**Comment by nicefaa6waa** [comment]
Thank youuu! I'm glad to hear that your previous issues have been helpful to others. If there's anything specific you'd like to discuss or need assistance with, feel free to let me know. Have a wonderful day!
