### ISSUE TITLE
Skip loading animation

### ISSUE THREAD

**Issue by wowlikon** [nicefaa6waa/genshin-sddm-theme#38]
Please add in the settings the ability to skip the loading animation. I tried to manually remove it from `Main.qml`, but because of this nothing happens after entering the password

**Comment by nicefaa6waa** [comment]
Working on it

**Comment by nicefaa6waa** [comment]
Added a feature to disable LoadingAnimation to Install Script.Testing and pushing the commit ASAP

**Comment by nicefaa6waa** [comment]
Fixed and pushed the issue.Please reopen this issue if you have any further questions or in case it doesn't work.Have a great day <3!!!

**Comment by wowlikon** [comment]
OK, thank you
