### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by TrentonWorthy23** [nicefaa6waa/genshin-sddm-theme#40]
i installed this theme and switched to it. logged out to test it out and now I can't log back in. whenever I type in the password (correctly, I made sure) and press enter nothing happens, the password slot just goes blank again.
My OS is Linux Mint 21.3
My GPU is a Nvidia GeForce GTS 1650 Super.
Everything else about the theme works, besides the music. that stopped playing after I rebooted and didn't start up again either, but I'm much more worried about not being able to log in.

**Comment by nicefaa6waa** [comment]
If your music isn't working, it might be due to operating system issues. Interestingly, music works on some OSs and not on others. Sometimes, even reinstalling the OS can make it start working unexpectedly. I will look into this issue in the future.

Updating Theme Credentials

If you suspect you entered your password incorrectly while installing the theme using the installation script, follow these steps to resolve the issue:

   Edit the Credentials File:
       Navigate to the components directory in your theme installation folder.
        Locate and open the credentials.txt file.

   Update Your Username and Password:
       Add your username and password in the following format:

  ``username:password``

 Make sure to replace username and password with your actual username and password.

   Save and Close:
       Save the changes to the credentials.txt file and close it.

This should fix any issues related to the theme credentials.

**Comment by TrentonWorthy23** [comment]
That's not the actual problem, the problem is I can't even log in. pressing enter does nothing. pressing the button that says "Login!!" does nothing. I _know_ that I'm inputting the correct password, and it still won't log me in.
If I could figure out a way to switch themes in the console, that would fix my issue, I'm sure, because I can still enter tty4. So I can't access my files and check the themes folder anyway, at least not with Dolphin manager. (oh yeah, probably should have mentioned my DE is KDE Plasma but I'm not really sure if that matters.
I've uploaded a small clip I recorded with my phone showing me click on the login button as an example (if it actually uploaded and embeds properly, I'm on mobile) to show what happens.

https://github.com/user-attachments/assets/3e28877b-0d47-4c43-8d1f-b5a451e7d85d

**Comment by nicefaa6waa** [comment]
Well you can go to tty4 then cd into
/usr/share/sddm/themes/genshin-sddm-theme/components/
then you can edit the credentials file using nano.Keep in mind you need sudo permissions.So step by step
```
cd /usr/share/sddm/themes/genshin-sddm-theme/components/ (Or without the backslash at first like usr/share)
sudo nano credentials.txt
Then add your username and password as
username:password
Then ctrl + o to save then say yes.
After that just restart
```
From your issue it is obvious that you didn't add your credentials to credentials.txt file.Just do as i said and it will be fixed.

**Comment by nicefaa6waa** [comment]
It is not about you inputting the correct password or not.This theme reads the correct username and password from credentials.txt file(It is necessary for the door animations too complicated to explain).So as long as your username and password for it isn't in credentials.txt file you won't be able to login.Just add your username and password as i explained.

**Comment by nicefaa6waa** [comment]
Also i think your background video doesn't move?
Well thats probably because of bad dependancies.If you are new to linux and need help with something i can help you with it.If you need further assitance i can text you from somewhere else your discord or another social media account.Just let me know <3

**Comment by TrentonWorthy23** [comment]
I figured it out. I just had to add a file to the sddm.conf.d directory that changes the theme so I can log in. unfortunate that the theme doesn't work on my system, as it is really cool.

**Comment by nicefaa6waa** [comment]
I’m glad to hear that you fixed the issue! (˶ᵔ ᵕ ᵔ˶) To get it running on KDE, make sure you add your credentials to the credentials.txt file as explained.

For a smoother and more compatible installation, I recommend deleting the current theme through KDE settings first. Then, clone the repository using git clone and run the automated installer script (bash instal-sddm-theme.sh). This will automatically fix any login issues.

Please read the README file thoroughly, as it contains all the necessary details.Thank you for your interest, and have a lovely day!

<3

P.S. I will try to add an automated credential grabber for the KDE Store, but it may be hard and insecure.

**Comment by nicefaa6waa** [comment]
Oh and also even if you don't change the credentials.txt the default username and password is 
churchy:123123
You can see the theme is working by putting these credentials.

**Comment by CARDZYY** [comment]
> Saya sudah menemukan jawabannya. Saya hanya perlu menambahkan file ke direktori sddm.conf.d yang mengubah tema sehingga saya bisa masuk. Sayangnya tema tersebut tidak berfungsi di sistem saya, padahal tema tersebut sangat keren.

Bagaimana cara kamu login?

**Comment by tiamed** [comment]
Installed and applied from kde settings > Colors & Themes > SDDM, also unable to login.

**Comment by nicefaa6waa** [comment]
For those following the tutorial in the README, there's a section explaining how to change the default password. Before you can update it, make sure you're able to log in using the default credentials:

- Username: churchy
- Password: 123123

Once logged in, follow the steps outlined in the README or previous comments to change the password.
