### ISSUE TITLE
While trying to install I believe theres an sudo missing 

### ISSUE THREAD

**Issue by DarkevilPT** [nicefaa6waa/genshin-sddm-theme#43]
![image](https://github.com/user-attachments/assets/6655fda9-33bf-49af-bdd5-a01432fb3fbb)

**Comment by nicefaa6waa** [comment]
clone the repo to somewhere like your Home or Downlaods folder.After that use chmod +x <file_name> replace rhe file name with installer script and try again

**Comment by nicefaa6waa** [comment]
Closed as no response and it is not an issue <3.Re-open this issue if you have any more questions tho

**Comment by DarkevilPT** [comment]
I didnt replied because I had eventually installed it but upon reboot typing password wouldnt enter the system and then not even the video played and it looked messed up I def failed to do some more manually steps so I gave up.. im sure it works if done right.. but im also using an arm64 sbc the khadas edge 2 and cant say if it will crack on mine right so.. meh

**Comment by nicefaa6waa** [comment]
Ohh..Sorry to hear that.arm64 sbc may be causing some issues i actually don't have any idea.Please let me know if i can help somehow.

**Comment by DarkevilPT** [comment]
Nah no worries man keep up the good work.
I love customised stuff.
Im cooking a wee guide here: https://forum.khadas.com/t/guide-arch-linux-installer-on-edge-2/21369/1

If you wanna check.. maybe try an rk3588 board.. I also own the radxa cm5 this is addictive if u dive deep into this ..  u will love. 

Cheers!
