### ISSUE TITLE
Can I set virtual keyboard disabled?

### ISSUE THREAD

**Issue by naruko-hstk** [nicefaa6waa/genshin-sddm-theme#7]
![image](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/34113239/7374a725-a570-495c-8450-cab6e60a2b0f)

**Comment by nicefaa6waa** [comment]
Hi.I don't remember implementing anything about virtual keyboard.It may be related to your Os or sddm config.If you can inform me abiut the device you are using i can try to help.Also will commit a new optimized settings so may wait for it.

**Comment by nicefaa6waa** [comment]
Hi.I don't remember implementing anything about virtual keyboard.It may be related to your Os or sddm config.If you can inform me abiut the device you are using i can try to help.Also will commit a new optimized settings so may wait for it.

**Comment by nicefaa6waa** [comment]
> ![image](https://github.com/nicefaa6waa/genshin-sddm-theme/assets/34113239/7374a725-a570-495c-8450-cab6e60a2b0f)
> 

Closed because no reply

**Comment by nicefaa6waa** [comment]
Found out that virtual keyboard is enabled on sddm by default for some reason.Will fix it in install script.

**Comment by nicefaa6waa** [comment]
Now while installing with install script you can set virtual keyboard on and off
